"""T9: Add user_skill_snapshots table for AC12

Revision ID: c1d2e3f4a5b6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-29 23:50:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1d2e3f4a5b6"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_skill_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_name", sa.String(length=64), nullable=True),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("path_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["learning_paths.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_skill_snapshots_id"), "user_skill_snapshots", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_skill_snapshots_user_id"), "user_skill_snapshots", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_skill_snapshots_user_id"), table_name="user_skill_snapshots")
    op.drop_index(op.f("ix_user_skill_snapshots_id"), table_name="user_skill_snapshots")
    op.drop_table("user_skill_snapshots")
    # ### end Alembic commands ###
