"""T10: Add job_skill_requirements table for AC13

Revision ID: d1e2f3a4b5c6
Revises: c1d2e3f4a5b6
Create Date: 2026-05-30 00:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1e2f3a4b5c6"
down_revision: Union[str, None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_skill_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_title", sa.String(length=64), nullable=False),
        sa.Column("job_level", sa.String(length=16), nullable=True),
        sa.Column("required_skills", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_skill_requirements_id"), "job_skill_requirements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_job_skill_requirements_job_title"),
        "job_skill_requirements",
        ["job_title"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_skill_requirements_job_title"), table_name="job_skill_requirements")
    op.drop_index(op.f("ix_job_skill_requirements_id"), table_name="job_skill_requirements")
    op.drop_table("job_skill_requirements")
    # ### end Alembic commands ###
