"""T6: Add Radar module tables

Revision ID: e1f2g3h4i5j6
Revises: b2c3d4e5f6a7
create_date: 2026-05-31 07:50:00.000000

T6: Radar 模块数据库表 — 技能维度、技能事件
AC覆盖: AC7, AC9
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1f2g3h4i5j6"
down_revision: str = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create skill_dimensions table
    op.create_table(
        "skill_dimensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("name_en", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("weight_formula", sa.Text(), nullable=True),
        sa.Column("max_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_skill_dimensions_id"), "skill_dimensions", ["id"], unique=False)
    op.create_index(op.f("ix_skill_dimensions_slug"), "skill_dimensions", ["slug"], unique=True)

    # Create skill_events table
    op.create_table(
        "skill_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=True),
        sa.Column("score_impact", sa.Float(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["skill_dimensions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_events_id"), "skill_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_skill_events_created_at"), "skill_events", ["created_at"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skill_events_created_at"), table_name="skill_events")
    op.drop_index(op.f("ix_skill_events_id"), table_name="skill_events")
    op.drop_table("skill_events")
    op.drop_index(op.f("ix_skill_dimensions_slug"), table_name="skill_dimensions")
    op.drop_index(op.f("ix_skill_dimensions_id"), table_name="skill_dimensions")
    op.drop_table("skill_dimensions")
    # ### end Alembic commands ###
